
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: mvm_development

test:
  <<: *default
  database: mvm_test


production:
  <<: *default
  database: mvm_production
  username: mvm
  password: <%= ENV['MVM_DATABASE_PASSWORD'] %>
